### ISSUE TITLE
Lora: not all my lora's are showing

### ISSUE THREAD

**Issue by rafstahelin** [eideehi/sd-webui-better-prompt#10]
Hey, Not all my lora's show. Is there a setting or something that determines whether the lora gets recognised and sent to the suggestion area? I can clearly see some lora's that actually are seen in the lora module of webui are not showing on suggestion. Have a feeling it has something to do with the instance prompt. Is it a problem if the instance prompt is contained in the lora filename? Not sure. Would be nice to resolve this issue/non-issue thansks

**Comment by eideehi** [comment]
The information for LoRA is obtained by parsing the HTML of the Lora tab in Extra Networks. No filtering is applied. Additionally, LoRA list is checked for updates every second. It is puzzling that LoRA appearing in Extra Networks does not appear in the suggestions. Please press the F12 key to launch the developer tools and check if any errors are displayed in the console.
