### ISSUE TITLE
Dynamic Promot Wildcards integration

### ISSUE THREAD

**Issue by rafstahelin** [eideehi/sd-webui-better-prompt#11]
Feel like this might be a super enhancement for better prompts to have direct access to the prompt dynamic prompt folder of txt wildcards in order to directly insert the __wildcart.txt__ into the prompt right from better prompt... this would be godsend

**Comment by eideehi** [comment]
For maintainability and compatibility, i have a policy of not implementing integration features with other extensions, except for a few exceptions. Regarding this proposal, I believe it can be addressed with the planned alias feature, which we will implement in the future.
