### ISSUE TITLE
Laggy 

### ISSUE THREAD

**Issue by rafstahelin** [eideehi/sd-webui-better-prompt#12]
Hey, I am getting quite a lot of lag on the lattest gradio. I dont actually have experience with previous versions of ewbui, but in this one, after i type some prompts, it takes a while to update the buttons underneath. Each letter comes in at 1/5 speed. Very slow. Very unusable. I need to do some testing to see if another extension is conflicting, but this is happening before any generating even happens

**Comment by wogam** [comment]
It's still very laggy for me, though no errors in the developer console. Using latest version of better prompt and the only other extension I have is ControlNet.
