### ISSUE TITLE
[Issue]: Selected LoRAs doesn't follow Multiplier Setting.

### ISSUE THREAD

**Issue by brknsoul** [eideehi/sd-webui-better-prompt#13]
When using Better Prompt to add a LoRA to your prompt it should follow "Multiplier for extra networks" in Settings > Extra Networks.

Currently it adds the LoRA at strength 1.0.

**Comment by eideehi** [comment]
I will fix it.

**Comment by eideehi** [comment]
This issue has been fixed in version 0.4.0.
